// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:62704641227:web:954adacd2afbfc0f03e74e',
    messagingSenderId: '62704641227',
    projectId: 'kata-terbina',
    authDomain: 'kata-terbina.firebaseapp.com',
    storageBucket: 'kata-terbina.firebasestorage.app',
    measurementId: 'G-TSB6ZBH7SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPV1FVsTBFcR1ZKJW_El9cSEC09aF4ns',
    appId: '1:62704641227:android:87d3413f607a0bfc03e74e',
    messagingSenderId: '62704641227',
    projectId: 'kata-terbina',
    storageBucket: 'kata-terbina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:62704641227:ios:26e6eba9549c1eff03e74e',
    messagingSenderId: '62704641227',
    projectId: 'kata-terbina',
    storageBucket: 'kata-terbina.firebasestorage.app',
    iosBundleId: 'com.example.kataTerbina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqBDBX8kmWkP-Elv1ZXHoyzJMKFjhOH5o',
    appId: '1:62704641227:ios:26e6eba9549c1eff03e74e',
    messagingSenderId: '62704641227',
    projectId: 'kata-terbina',
    storageBucket: 'kata-terbina.firebasestorage.app',
    iosBundleId: 'com.example.kataTerbina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_1bSvGWiA-Tw1ki263IBXjr0NjBFxYn8',
    appId: '1:62704641227:web:e5896dad8316e73f03e74e',
    messagingSenderId: '62704641227',
    projectId: 'kata-terbina',
    authDomain: 'kata-terbina.firebaseapp.com',
    storageBucket: 'kata-terbina.firebasestorage.app',
    measurementId: 'G-8K3VQZ50YF',
  );
}
